---

- name: Ensure etcd config directory exists
  file:
    path: "{{ etcd_config_dir }}"
    recurse: yes
    state: directory

- name: Ensure etcd data directory exists
  file:
    path: "{{ etcd_data_dir }}"
    recurse: yes
    state: directory

- name: Copy etcd config template file
  template: src=etcd-config.yml.j2 dest={{ etcd_config_file }}
