---

- name: Copy etcd systemd service file
  template:
    src: etcd.service.j2
    dest: "{{ systemd_service_dir }}/etcd.service"
    owner: root
    group: root
    mode: 0644
  register: change_etcd

- name: Enable and restart etcd
  when: change_etcd
  systemd:
    name: etcd
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_etcd
